export const API_URL = import.meta.env.VITE_API_URL ?? ''

export const ENDPOINTS = {
  GET_USER_INFO: '/api/User/GetUserInfo',
  GET_LOCATION_HIERARCHY: '/api/Auxiliary/GetLocationHierarchy',
  GET_ALL_BANNERS: '/api/AuditPackage/RetrieveAllBanners',
  CREATE_BANNER: '/api/AuditPackage/CreateBanner',
  UPDATE_BANNER_STATUS: '/api/AuditPackage/UpdateBannerStatus',
  DELETE_BANNER: '/api/AuditPackage/DeleteBanner',
  CREATE_TOOLS: '/api/Tools/CreateAuditTools',
  DELETE_TOOL: '/api/Tools/DeleteAuditTool',
  GET_BANNER_BY_PACKAGE_ID: '/api/AuditPackage/GetBannerBasedOnPackageID',
  GET_TOOLS_BY_PACKAGE_ID: '/api/Tools/GetAuditTools',
  GET_LOCATIONS_BY_PACKAGE_ID: '/api/AuditPackage/GetBannerLocations',
  GET_TOOL_TEMPLATES_BY_LOCATION_ID: '/api/Tools/GetAuditToolTemplates',
  GET_QUESTIONS_BY_PACKAGE_TEMPLATE_ID: '/api/Form/GetQuestions',
  UPDATE_TOOL_STATUS: '/api/Tools/UpdateToolStatus',
  SAVE_ANSWER: '/api/Form/SaveAnswer',
  SUBMIT_ANSWERS: '/api/Form/SubmitAnswers',
  UPLOAD_ATTACHMENT: '/api/Services/CreateAttachments',
  GET_ATTACHMENTS: '/api/Services/GetAttachments',
  DOWNLOAD_ATTACHMENT: '/api/Services/DownloadAttachment',
  DELETE_ATTACHMENT: '/api/Services/DeleteAttachments',
  GET_NOTIFICATION_USERS: '/api/Services/GetNotificationUsers',
  GET_CAPA_DETAILS: '/api/CAPA/GetCAPADetails',
  CREATE_CAPA: '/api/CAPA/PostCreateCAPA',
  UPDATE_CAPA: '/api/CAPA/PutCAPAUpdate',
  GET_CAPA_STATUS: '/api/CAPA/RetrievePossibleStatus',
  SUBMIT_CAPA: '/api/CAPA/PutCAPAUpdateStatus',
  SEND_CAPA_NOTIFICATION: '/api/CAPA/SendCAPANotification',
  GET_TEAM_AUDITORS: '/api/AuditTeams/GetTeamAuditors',
  GET_ASSIGNED_TEAM_MEMBERS: '/api/AuditTeams/GetAssignedTeamMembers',
  MANAGE_TEAM_AUDITORS: '/api/AuditTeams/ManageTeamAuditors',
  REASSIGN_AUDITOR: '/api/AuditTeams/ReassignAuditor',
  REASSIGN_TEAM_LEAD: '/api/AuditTeams/ReassignLead',
  MAINTENANCE_TOOLS: '/api/Maintenance/GetMaintenanceAuditTools',
  MAINTENANCE_BUSINESSLINES: '/api/Maintenance/GetMaintenanceBusinessLines',
  TEMPLATE_QUESTIONS: '/api/Maintenance/GetTemplateDetails',
  UPDATE_MAINTENANCE_QUESTION: '/api/Maintenance/UpdateQuestions',
  CREATE_TEMPLATE: '/api/Maintenance/CreateTemplate',
  UPDATE_TEMPLATE: '/api/Maintenance/UpdateTemplate',
  CREATE_MAINTENANCE_QUESTION: '/api/Maintenance/CreateQuestions',
  DELETE_TEMPLATE_QUESTION: '/api/Maintenance/DeleteQuestions',
  PUBLISH_TEMPLATE: '/api/Maintenance/PublishQuestions'
}
